package com.nsfwcyoamaker.cotdr.presentation.screens.rulings

import com.nsfwcyoamaker.cotdr.presentationToadHandler.ViewAction

interface RulingsSelectionAction: ViewAction<RulingsSelectionActionDependencies, RulingsSelectionState, Nothing>